### ISSUE TITLE
HTC Android device not redirected to splash page

### ISSUE THREAD

**Issue by max-b** [sudomesh/garden-gnome#1]
Was testing an HTC Android device and it did a GET request for the clients3.google.com/generate_204 page and after redirecting, showed a notification to "sign into network".

But then when I clicked on the notification, it opened a web browser to http://htc.us

I don't know how we'd handle this except for much more intrusive filtering...

**Comment by paidforby** [comment]
splash page never implemented, reopen if still an issue once implemented
