### ISSUE TITLE
IOS 9 Won't connect to internet

### ISSUE THREAD

**Issue by max-b** [sudomesh/garden-gnome#2]
Daniel and I were testing the splash page with his new iphone and it was refusing to acknowledge that it was connected to the internet because the way that the portal redirects were being captured.

It should be an easy enough fix. I had been sort of hoping that I wouldn't need to track individual users' IP addresses over time, but it looks like I'll need to open up the iptables rules or at least keep track of which users to stop proxying the requests from.

**Comment by Juul** [comment]
On Mon, Jan 18, 2016 at 12:11 PM, maxb notifications@github.com wrote:

> Daniel and I were testing the splash page with his new iphone and it was
> refusing to acknowledge that it was connected to the internet because the
> way that the portal redirects were being captured.
> 
> It should be an easy enough fix. I had been sort of hoping that I wouldn't
> need to track individual users' IP addresses over time, but it looks like
> I'll need to open up the iptables rules or at least keep track of which
> users to stop proxying the requests from.

Yes. How would it even work if it didn't keep track of which IPs have
already clicked through? We had a whole discussion about this back when we
were using batman-adv and we really didn't want to track MAC addresses.

## 

marc/juul

**Comment by max-b** [comment]
It actually works just fine on every OS except for iOS 9 right now without keeping track of IPs that have clicked through.

The portal probes only occur when a device is connecting to a new ssid. So when you connect to the network, the probe is caught and the splash page appears. And then you can go on connecting to the rest of the internet without ever having to track ip addresses. iOS9 is the only OS that then proceeds to panic when its probes continue to be blocked.

**Comment by Juul** [comment]
On Mon, Jan 18, 2016 at 12:45 PM, maxb notifications@github.com wrote:

> It actually works just fine on every OS except for iOS 9 right now without
> keeping track of IPs that have clicked through.
> 
> The portal probes only occur when a device is connecting to a new ssid. So
> when you connect to the network, the probe is caught and the splash page
> appears. And then you can go on connecting to the rest of the internet
> without ever having to track ip addresses. iOS9 is the only OS that then
> proceeds to panic when its probes continue to be blocked.
> 
> Odd. I definitely had the same problem with an earlier iOS and just assumed
> it was the standard behavior.

## 

marc/juul

**Comment by max-b** [comment]
Ok this is fixed in https://github.com/sudomesh/garden-gnome/commit/b1a45734b5d175bd50a1630a8b8d08a54c052693
