### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by thebalaa** [sudomesh/garden-gnome#5]
Not getting any kind of splash page on Windows 10
- wifi connection manager temporarily reports "No Internet" 
- internet is working

**Comment by max-b** [comment]
hey @thebalaa any chance you'd be able to run tcpdump while this is going on to see the traffic pattern? According to http://blog.superuser.com/2011/05/16/windows-7-network-awareness/ I should be blocking the correct urls, but it's possible that article is out of date for win 10.

**Comment by thebalaa** [comment]
hm, I just got the "Attention required for peoplesopen.net" bubble in the lower left part of my screen, when I clicked it I was directed to http://www.msn.com/?ocid=wispr

**Comment by max-b** [comment]
wtf... ok I _could_ just add that url to the portal probe urls, or I could spin up a virtual machine or something to do some more/better testing...

**Comment by thebalaa** [comment]
maybe this could help: https://msdn.microsoft.com/en-us/library/windows/hardware/dn408681.aspx

**Comment by paidforby** [comment]
garden gnome no longer maintained
